#!/usr/bin/env python3
"""Query the lightweight Obsidian recall index.

This is a small Cognee-inspired retrieval layer: it does not require a vector
database, graph database, Docker, or an LLM. It ranks structured memory units
generated by knowledge_index.py.
"""
import argparse
import json
import math
import os
import re
import sys
from datetime import date, datetime

from experience_memory import (
    has_experience_intent,
    select_experience_companions,
    validate_experience_bundles,
)
from conversation_summary import (
    conversation_summary_search_text,
    validate_conversation_summary_record,
)
from knowledge_index import (
    enrich_runtime_unit,
    extract_terms,
    is_session_memory_path,
    type_rank,
)
from memory_authority import authority_rank, authority_route, normalize_authority_metadata
from memory_graph import (
    GRAPH_FILENAME,
    graph_path_for_index,
    semantic_memory_paths,
    validate_memory_graph,
)
from memory_schema import (
    RUNTIME_SCHEMA_VERSION,
    canonical_project,
    is_valid_runtime_record,
    runtime_source_path,
)


DEFAULT_INDEX = os.path.join("05-Agent-Memory", "recall-index.json")
RUNTIME_METADATA_FIELDS = frozenset(
    {"_graph", "_graph_quality", "_graph_validated", "_path"}
)
RETRIEVAL_CHANNELS = (
    "lexical",
    "structured",
    "type",
    "temporal",
    "graph",
    "experience",
)
RETRIEVAL_CHANNEL_WEIGHTS = {
    "lexical": 1.0,
    "structured": 0.8,
    "type": 0.45,
    "temporal": 0.6,
    "graph": 0.35,
    "experience": 0.3,
}
RRF_K = 60
RRF_SCORE_SCALE = 1000
TYPE_INTENT_RULES = (
    (
        frozenset({"preference"}),
        re.compile(r"(?:个人偏好|用户偏好|偏好|喜好|习惯|\bpreferences?\b)", re.IGNORECASE),
    ),
    (
        frozenset({"project_rule"}),
        re.compile(r"(?:项目规则|项目约定|\bproject rules?\b)", re.IGNORECASE),
    ),
    (
        frozenset({"environment"}),
        re.compile(r"(?:开发环境|电脑环境|环境配置|\benvironment\b)", re.IGNORECASE),
    ),
    (
        frozenset({"decision"}),
        re.compile(r"(?:决策|决定|技术选择|选型|\bdecisions?\b)", re.IGNORECASE),
    ),
    (
        frozenset({"error"}),
        re.compile(r"(?:错误|报错|异常|失败|故障|\b(?:errors?|bugs?|failures?|pitfalls?)\b)", re.IGNORECASE),
    ),
    (
        frozenset({"skill"}),
        re.compile(r"(?:技能偏好|技能路由|技能|\bskills?\b)", re.IGNORECASE),
    ),
    (
        frozenset({"workflow"}),
        re.compile(r"(?:工作流|流程记忆|流程规则|\bworkflows?\b)", re.IGNORECASE),
    ),
    (
        frozenset({"insight"}),
        re.compile(r"(?:启发|洞见|灵感|思路|\binsights?\b|\binspiration\b)", re.IGNORECASE),
    ),
)
INVENTORY_QUERY_PATTERN = re.compile(
    r"(?:有哪些|哪些|有什么|全部|所有|列出|清单|汇总|"
    r"\b(?:list|show|which|what\s+(?:are|is))\b)",
    re.IGNORECASE,
)
LATEST_QUERY_PATTERN = re.compile(
    r"(?:最近|最新|上次|刚才|\b(?:latest|recent|last)\b)",
    re.IGNORECASE,
)
EARLIEST_QUERY_PATTERN = re.compile(
    r"(?:最早|最初|第一次|\b(?:earliest|oldest|first)\b)",
    re.IGNORECASE,
)
SINGLE_TEMPORAL_QUERY_PATTERN = re.compile(
    r"(?:一次|一个|上次|第一次|\b(?:last one|latest one|first one)\b)",
    re.IGNORECASE,
)
EXPLICIT_DATE_PATTERN = re.compile(
    r"(?P<year>20\d{2})(?:[-/.年](?P<month>\d{1,2}))?"
    r"(?:[-/.月](?P<day>\d{1,2})日?)?"
)
QUERY_FILLER_PATTERN = re.compile(
    r"(?:是什么|为什么|怎么办|有什么|有哪些|哪些|什么|怎么|如何|为何|"
    r"请|麻烦|给我|帮我|帮忙|一下|一个|这个|那个|这些|那些|相关|关于|"
    r"修复|解决|处理|问题|"
    r"\b(?:what|which|how|why|please|show|list|"
    r"fix(?:ed|es|ing)?|repair(?:ed|s|ing)?|"
    r"issues?|problems?)\b)",
    re.IGNORECASE,
)
INSPIRATION_ACTION_PATTERN = re.compile(
    r"(?:设计|架构|新方案|替代方案|其他方案|换个角度|换条路|比较|借鉴|"
    r"类比|创新|拓展|发散|脑暴|卡住|启发|洞见|灵感|思路|"
    r"\b(?:design|architect(?:ure)?|alternatives?|compare|analogy|"
    r"brainstorm|innovate|inspiration|insights?|stuck)\b)",
    re.IGNORECASE,
)
INSPIRATION_WEAK_CONTENT_PATTERN = re.compile(
    r"(?:功能|系统|程序|项目|东西|内容|任务|方案|方法|角度|"
    r"\b(?:feature|system|program|project|thing|task|plan|method)\b)",
    re.IGNORECASE,
)
CONVERSATION_SUMMARY_INTENT_PATTERN = re.compile(
    r"(?:滚动)?(?:会话|对话)?摘要|上下文|"
    r"\bsummar(?:y|ies)\b|"
    r"\b(?:rolling\s+)?(?:conversation|session)\s+summar(?:y|ies)\b|"
    r"\bconversation\s+context\b",
    re.IGNORECASE,
)
CONVERSATION_SUMMARY_WEAK_ENGLISH_PATTERN = re.compile(
    r"\b(?:status|state|progress|updates?|recall|retrieval|retrieve[ds]?|"
    r"current|active|latest|recent|last|conversation|session|memory|"
    r"goals?|tasks?|topics?|constraints?|items?|details?|information|info|"
    r"overview|work|working|done|pending)\b",
    re.IGNORECASE,
)
CONVERSATION_SUMMARY_GENERIC_CHINESE_TERMS = frozenset(
    {
        "状态", "进度", "进展", "更新", "召回", "检索", "记录", "会话",
        "对话", "最近", "最新", "上次", "目标", "任务", "主题", "待办",
        "约束", "重要", "信息", "内容", "详情", "工作", "完成", "未完成",
        "摘要", "滚动摘要", "上下文", "是什么", "为什么", "怎么办",
        "有什么", "有哪些", "哪些", "什么", "怎么", "如何", "为何", "请",
        "麻烦", "给我", "帮我", "帮忙", "一下", "一个", "这个", "那个",
        "这些", "那些", "相关", "关于", "修复", "解决", "处理", "问题",
        "全部", "所有", "列出", "清单", "汇总", "刚才", "最早", "最初",
        "第一次", "一次", "我们", "你们", "我", "你", "之前", "聊了",
        "聊过", "聊", "说了", "说过", "说", "看", "看看", "告诉",
        "告诉我", "当前", "目前", "现在", "的", "了", "吗", "呢", "啊",
        "吧",
    }
)
CONVERSATION_SUMMARY_GENERIC_CHINESE_PATTERN = re.compile(
    r"^(?:"
    + "|".join(
        re.escape(term)
        for term in sorted(
            CONVERSATION_SUMMARY_GENERIC_CHINESE_TERMS,
            key=lambda term: (-len(term), term),
        )
    )
    + r"|[\s，。！？、；：,.!?;:（）()\[\]{}])+$"
)


def load_recall_index(vault_or_index_path):
    """Load recall-index.json from a vault path or direct file path."""
    path = os.path.expanduser(os.path.expandvars(str(vault_or_index_path or "")))
    if os.path.isdir(path):
        path = os.path.join(path, DEFAULT_INDEX)
    if not os.path.exists(path):
        raise FileNotFoundError(f"recall index not found: {path}")
    with open(path, "r", encoding="utf-8") as handle:
        data = json.load(handle)
    graph_path = graph_path_for_index(path)
    graph = None
    if os.path.exists(graph_path):
        with open(graph_path, "r", encoding="utf-8") as handle:
            graph = json.load(handle)
        if not isinstance(graph, dict):
            raise ValueError(f"memory graph is not a JSON object: {graph_path}")
    return prepare_recall_index(data, path=path, graph=graph)


def prepare_recall_index(data, *, path="", graph=None):
    """Validate already-read index data and attach optional graph metadata."""
    if not isinstance(data, dict):
        raise ValueError(f"recall index is not a JSON object: {path}")
    data = {
        key: value
        for key, value in data.items()
        if key not in RUNTIME_METADATA_FIELDS
    }
    validate_recall_index(data)
    data["_path"] = str(path or "")
    if graph is not None:
        if not isinstance(graph, dict):
            raise ValueError("memory graph must be a JSON object")
        if graph.get("schema_version") == "3.0" and not data.get("generation_id"):
            raise ValueError("recall index generation_id is required for Graph v3")
        data["_graph_quality"] = validate_memory_graph(
            graph,
            data.get("units"),
            allow_legacy=False,
            expected_generation_id=data.get("generation_id", ""),
        )
        data["_graph"] = graph
        data["_graph_validated"] = True
    return data


def recall(
    query,
    index,
    project="",
    limit=8,
    *,
    allowed_projects=None,
    type_boosts=None,
    minimum_score=1,
    relative_score_threshold=0.0,
):
    """Return formal memory ranked through deterministic multi-channel fusion."""
    query = str(query or "").strip()
    if not query:
        return []
    validate_recall_index(index)
    raw_project = str(project or "").strip()
    project = canonical_project(raw_project)
    if raw_project and not project:
        return []
    normalized_allowed = _canonical_projects(allowed_projects)
    type_boosts = dict(type_boosts or {})
    query_text = normalize(query)
    content_query = extract_content_query(query_text)
    query_terms = set(extract_terms(content_query, limit=40))
    if not query_terms:
        content_query = ""
    relative_score_threshold = float(relative_score_threshold or 0)
    if not 0 <= relative_score_threshold <= 1:
        raise ValueError("relative_score_threshold must be between 0 and 1")

    eligible_units = []
    for unit in index.get("units", []):
        if not is_runtime_unit(unit):
            continue
        if not _unit_allowed(unit, project, normalized_allowed):
            continue
        eligible_units.append(enrich_runtime_unit(unit))
    units_by_id = {
        unit["id"]: unit
        for unit in eligible_units
        if unit.get("id")
    }

    term_weights = query_term_weights(query_terms, eligible_units)
    lexical_scores = {}
    structured_scores = {}
    for unit in eligible_units:
        unit_id = unit.get("id")
        lexical_score = score_unit(
            unit,
            content_query,
            query_terms,
            term_weights=term_weights,
        )
        if lexical_score > 0:
            lexical_score += float(type_boosts.get(unit.get("type"), 0) or 0)
            if lexical_score >= float(minimum_score):
                lexical_scores[unit_id] = lexical_score
        structured_score = (
            score_structured_unit(unit, query_text)
            if query_terms
            else 0
        )
        if structured_score > 0:
            structured_scores[unit_id] = structured_score

    type_intents = infer_type_intents(query_text)
    inventory_query = bool(INVENTORY_QUERY_PATTERN.search(query_text))
    temporal_intent = infer_temporal_intent(query_text)
    anchored_ids = set(lexical_scores) | set(structured_scores)
    type_scores = build_type_scores(
        eligible_units,
        type_intents,
        anchored_ids,
        lexical_scores,
        structured_scores,
        allow_unanchored=inventory_query or bool(temporal_intent),
    )
    temporal_scores = build_temporal_scores(
        eligible_units,
        temporal_intent,
        type_intents=type_intents,
        anchored_ids=anchored_ids,
        has_content_query=bool(query_terms),
    )

    singular_temporal_query = bool(
        temporal_intent and temporal_intent.get("limit")
    )
    if singular_temporal_query:
        direct_ids = set(temporal_scores)
    else:
        direct_ids = set(anchored_ids)
        if inventory_query:
            direct_ids.update(type_scores)
        if temporal_intent and type_intents:
            direct_ids.update(set(type_scores) & set(temporal_scores))

    direct_results = []
    for unit_id in sorted(direct_ids):
        unit = units_by_id.get(unit_id)
        if not unit:
            continue
        result = dict(unit)
        result["score"] = max(
            lexical_scores.get(unit_id, 0),
            structured_scores.get(unit_id, 0),
        )
        result["match_kind"] = "direct"
        direct_results.append(result)

    # Graph expansion starts only from content-anchored memories. Generic list or
    # time queries must not fan out through every note linked to the requested type.
    graph_seeds = [] if singular_temporal_query else [
        item for item in direct_results if item.get("id") in anchored_ids
    ]
    graph_expanded = expand_graph_results(
        index,
        graph_seeds,
        project,
        allowed_projects=normalized_allowed,
    )
    graph_scores = {
        item["id"]: float(item.get("graph_score", item.get("score", 0)) or 0)
        for item in graph_expanded
        if item.get("id")
        and (
            item.get("match_kind") == "graph"
            or item.get("related_path")
        )
    }
    result_by_id = {item["id"]: item for item in direct_results}
    for item in graph_expanded:
        if item.get("id") in graph_scores:
            existing = result_by_id.get(item["id"])
            if existing is None:
                result_by_id[item["id"]] = item
                continue
            for key in (
                "graph_score",
                "related_confidence",
                "related_path",
                "related_seed",
                "related_via",
            ):
                if key in item:
                    existing[key] = item[key]

    experience_scores = {}
    if has_experience_intent(
        query_text,
        content_query=content_query,
        inventory_query=inventory_query,
    ):
        experience_seed_ids = sorted(
            anchored_ids,
            key=lambda unit_id: (
                max(
                    lexical_scores.get(unit_id, 0),
                    structured_scores.get(unit_id, 0),
                ),
                authority_rank(units_by_id.get(unit_id, {})),
                str(unit_id),
            ),
            reverse=True,
        )[:5]
        companions = select_experience_companions(
            index,
            experience_seed_ids,
            eligible_units,
            max_companions=2,
            max_bundles=1,
        )
        for unit, bundle_id in companions:
            unit_id = unit["id"]
            result = result_by_id.setdefault(unit_id, dict(unit))
            result["score"] = max(float(result.get("score") or 0), 1)
            result.setdefault("match_kind", "experience")
            result["related_experience"] = bundle_id
            experience_scores[unit_id] = 1

    channel_scores = {
        "lexical": lexical_scores,
        "structured": structured_scores,
        "type": {unit_id: score for unit_id, score in type_scores.items() if unit_id in result_by_id},
        "temporal": {
            unit_id: score
            for unit_id, score in temporal_scores.items()
            if unit_id in result_by_id
        },
        "graph": graph_scores,
        "experience": experience_scores,
    }
    rankings = {
        channel: rank_channel(scores, units_by_id, temporal=(channel == "temporal"))
        for channel, scores in channel_scores.items()
        if scores
    }
    results = fuse_rankings(
        result_by_id,
        rankings,
        channel_scores,
        temporal_intent=temporal_intent,
    )

    protected_insight_ids = {
        item.get("id")
        for item in results
        if item.get("id")
        and item.get("type") == "insight"
        and float(type_boosts.get("insight", 0) or 0) > 0
    }
    if results and relative_score_threshold:
        relative_cutoff = max(item["score"] for item in results) * relative_score_threshold
        results = [
            item
            for item in results
            if item["score"] >= relative_cutoff
            or item.get("id") in experience_scores
            or item.get("id") in protected_insight_ids
        ]

    results.sort(
        key=lambda item: (
            item["score"],
            authority_rank(item),
            insight_maturity_rank(item),
            type_rank(item.get("type", "")),
            str(item.get("date", "")),
            str(item.get("title", "")),
            recall_source_rank(item),
            str(item.get("project", "")),
            str(item.get("id", "")),
            str(item.get("path", "")),
        ),
        reverse=True,
    )
    selected = bounded_result_selection(
        dedupe_results(results),
        int(limit or 8),
        reserved_ids=set(experience_scores) | protected_insight_ids,
    )
    for item in selected:
        item["why_recalled"] = explain_retrieval(item, query_terms)
        item["authority"] = explain_authority(item)
    return selected


def recall_conversation_summaries(
    query,
    index,
    allowed_projects,
    limit=1,
):
    """Return at most one project-isolated summary through lexical evidence."""
    validate_recall_index(index)
    if not index.get("conversation_summaries"):
        return []
    try:
        requested_limit = int(limit)
    except (TypeError, ValueError):
        requested_limit = 0
    if requested_limit <= 0:
        return []

    query_text = normalize(query)
    query_text = CONVERSATION_SUMMARY_INTENT_PATTERN.sub(" ", query_text)
    query_text = CONVERSATION_SUMMARY_WEAK_ENGLISH_PATTERN.sub(" ", query_text)
    if _conversation_summary_query_is_generic(query_text):
        return []
    content_query = extract_content_query(
        query_text,
        strip_type_intents=False,
    )
    query_terms = set(extract_terms(content_query, limit=40))
    if not content_query or not query_terms:
        return []

    normalized_allowed = _canonical_projects(allowed_projects)
    eligible = []
    for record in index["conversation_summaries"]:
        if not _unit_allowed(record, "", normalized_allowed):
            continue
        trusted_search_text = conversation_summary_search_text(record)
        scoring_record = dict(record)
        scoring_record["summary"] = trusted_search_text
        scoring_record["terms"] = extract_terms(trusted_search_text)
        if not _summary_has_lexical_anchor(
            content_query,
            query_terms,
            scoring_record["terms"],
        ):
            continue
        eligible.append((record, scoring_record))
    if not eligible:
        return []

    term_weights = query_term_weights(
        query_terms,
        [scoring_record for _record, scoring_record in eligible],
    )
    ranked = []
    for record, scoring_record in eligible:
        score = score_unit(
            scoring_record,
            content_query,
            query_terms,
            term_weights=term_weights,
        )
        if score <= 0:
            continue
        result = dict(record)
        result["score"] = round(float(score), 6)
        result["match_kind"] = "conversation_summary"
        ranked.append(result)
    ranked.sort(
        key=lambda item: (
            float(item.get("score") or 0),
            str(item.get("date") or ""),
            str(item.get("title") or ""),
            str(item.get("session_id") or ""),
            str(item.get("id") or ""),
        ),
        reverse=True,
    )
    selected = ranked[:1]
    for rank, result in enumerate(selected, 1):
        result["retrieval_channels"] = ["conversation_summary"]
        result["retrieval_evidence"] = {
            "conversation_summary": {
                "rank": rank,
                "raw_score": result["score"],
            }
        }
    return selected


def _summary_has_lexical_anchor(content_query, query_terms, summary_terms):
    normalized_query = normalize(content_query)
    normalized_summary_terms = [
        normalize(term)
        for term in summary_terms
        if normalize(term)
    ]
    for query_term in expand_compound_terms(query_terms):
        normalized_term = normalize(query_term)
        if not normalized_term:
            continue
        if any(
            normalized_term in summary_term
            or summary_term in normalized_query
            for summary_term in normalized_summary_terms
        ):
            return True
    return False


def _conversation_summary_query_is_generic(query_text):
    query_text = normalize(query_text)
    return (
        not query_text
        or bool(
            CONVERSATION_SUMMARY_GENERIC_CHINESE_PATTERN.fullmatch(
                query_text
            )
        )
    )


def extract_content_query(query_text, *, strip_type_intents=True):
    """Remove retrieval intent words before building content anchors."""
    text = normalize(query_text)
    if strip_type_intents:
        for _, pattern in TYPE_INTENT_RULES:
            text = pattern.sub(" ", text)
    for pattern in (
        INVENTORY_QUERY_PATTERN,
        LATEST_QUERY_PATTERN,
        EARLIEST_QUERY_PATTERN,
        SINGLE_TEMPORAL_QUERY_PATTERN,
        EXPLICIT_DATE_PATTERN,
        QUERY_FILLER_PATTERN,
    ):
        text = pattern.sub(" ", text)
    text = normalize(text)
    if not re.search(r"[a-z0-9\u4e00-\u9fff]", text, re.IGNORECASE):
        return ""
    return text


def infer_type_intents(query_text):
    """Return only memory types explicitly named by the query."""
    intents = set()
    for memory_types, pattern in TYPE_INTENT_RULES:
        if pattern.search(query_text):
            intents.update(memory_types)
    return frozenset(intents)


def infer_inspiration_intent(query_text):
    """Require explicit exploration plus a concrete anchor, except inventories."""
    query_text = normalize(query_text)
    type_intents = infer_type_intents(query_text)
    if "insight" in type_intents and INVENTORY_QUERY_PATTERN.search(query_text):
        return True
    if not INSPIRATION_ACTION_PATTERN.search(query_text):
        return False
    content = extract_content_query(query_text)
    content = INSPIRATION_ACTION_PATTERN.sub(" ", content)
    content = INSPIRATION_WEAK_CONTENT_PATTERN.sub(" ", content)
    content = normalize(content)
    return bool(re.search(r"[a-z0-9]{3,}|[\u4e00-\u9fff]{2,}", content, re.IGNORECASE))


def infer_temporal_intent(query_text):
    """Return a narrow temporal intent that is safe to use without content terms."""
    explicit = EXPLICIT_DATE_PATTERN.search(query_text)
    if explicit:
        try:
            year = int(explicit.group("year"))
            month = int(explicit.group("month") or 1)
            day = int(explicit.group("day") or 1)
            target = date(year, month, day)
        except ValueError:
            return None
        precision = "day" if explicit.group("day") else "month" if explicit.group("month") else "year"
        return {"mode": "date", "target": target, "precision": precision}
    if LATEST_QUERY_PATTERN.search(query_text):
        return {
            "mode": "latest",
            "limit": 1 if SINGLE_TEMPORAL_QUERY_PATTERN.search(query_text) else None,
        }
    if EARLIEST_QUERY_PATTERN.search(query_text):
        return {
            "mode": "earliest",
            "limit": 1 if SINGLE_TEMPORAL_QUERY_PATTERN.search(query_text) else None,
        }
    return None


def build_type_scores(
    units,
    type_intents,
    anchored_ids,
    lexical_scores,
    structured_scores,
    *,
    allow_unanchored,
):
    if not type_intents:
        return {}
    scores = {}
    for unit in units:
        unit_id = unit.get("id")
        if unit.get("type") not in type_intents:
            continue
        if unit_id not in anchored_ids and not allow_unanchored:
            continue
        scores[unit_id] = max(
            lexical_scores.get(unit_id, 0),
            structured_scores.get(unit_id, 0),
            1,
        )
    return scores


def build_temporal_scores(
    units,
    temporal_intent,
    *,
    type_intents,
    anchored_ids,
    has_content_query,
):
    if not temporal_intent:
        return {}
    candidates = []
    for unit in units:
        unit_id = unit.get("id")
        if type_intents:
            if unit.get("type") not in type_intents:
                continue
            if has_content_query and unit_id not in anchored_ids:
                continue
        elif unit_id not in anchored_ids:
            continue
        ordinal = parse_memory_date(unit.get("date"))
        if ordinal is None:
            continue
        candidates.append((unit_id, ordinal))

    mode = temporal_intent["mode"]
    if mode == "latest":
        scores = {unit_id: ordinal for unit_id, ordinal in candidates}
        return limit_temporal_scores(scores, units, temporal_intent.get("limit"))
    if mode == "earliest":
        scores = {unit_id: -ordinal for unit_id, ordinal in candidates}
        return limit_temporal_scores(scores, units, temporal_intent.get("limit"))

    target = temporal_intent["target"]
    precision = temporal_intent["precision"]
    target_ordinal = target.toordinal()
    scores = {}
    for unit_id, ordinal in candidates:
        unit_date = date.fromordinal(ordinal)
        if precision == "year":
            distance = abs(unit_date.year - target.year) * 366
        elif precision == "month":
            distance = abs((unit_date.year - target.year) * 12 + unit_date.month - target.month) * 31
        else:
            distance = abs(ordinal - target_ordinal)
        scores[unit_id] = 1 / (1 + distance)
    return scores


def limit_temporal_scores(scores, units, limit):
    if not limit or len(scores) <= int(limit):
        return scores
    units_by_id = {unit.get("id"): unit for unit in units if unit.get("id")}
    ranked = rank_channel(scores, units_by_id, temporal=True)
    return {unit_id: scores[unit_id] for unit_id in ranked[: int(limit)]}


def parse_memory_date(value):
    raw = str(value or "").strip()
    if not raw:
        return None
    try:
        parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        try:
            parsed = datetime.strptime(raw[:10], "%Y-%m-%d")
        except ValueError:
            return None
    return parsed.date().toordinal()


def score_structured_unit(unit, query_text):
    """Score exact stable names such as a Skill, workflow, or error category."""
    score = 0
    values = (unit.get("name"), unit.get("title"))
    for value in values:
        normalized = normalize(value)
        if len(normalized) < 3:
            continue
        if structured_value_in_query(normalized, query_text):
            score += 12
        for part in re.findall(r"[a-z][a-z0-9]{2,}", normalized, re.IGNORECASE):
            if re.search(rf"(?<![a-z0-9]){re.escape(part)}(?![a-z0-9])", query_text, re.IGNORECASE):
                score += 4
    return score


def structured_value_in_query(value, query_text):
    if re.fullmatch(r"[a-z0-9_.:-]+", value, re.IGNORECASE):
        return bool(
            re.search(
                rf"(?<![a-z0-9]){re.escape(value)}(?![a-z0-9])",
                query_text,
                re.IGNORECASE,
            )
        )
    return value in query_text


def rank_channel(scores, units_by_id, *, temporal=False):
    """Return a deterministic best-first list for one retrieval channel."""
    def key(unit_id):
        unit = units_by_id.get(unit_id, {})
        score = float(scores.get(unit_id, 0))
        return (
            score,
            authority_rank(unit),
            type_rank(unit.get("type", "")),
            str(unit.get("date", "")) if not temporal else "",
            str(unit.get("title", "")),
            recall_source_rank(unit),
            str(unit.get("project", "")),
            str(unit_id),
            str(unit.get("path", "")),
        )

    return sorted(scores, key=key, reverse=True)


def fuse_rankings(
    result_by_id,
    rankings,
    channel_scores,
    *,
    temporal_intent,
):
    """Fuse independent rankings with weighted reciprocal rank fusion."""
    contributions = {}
    evidence = {}
    for channel in RETRIEVAL_CHANNELS:
        ranking = rankings.get(channel, ())
        weight = RETRIEVAL_CHANNEL_WEIGHTS[channel]
        for rank, unit_id in enumerate(ranking, start=1):
            if unit_id not in result_by_id:
                continue
            contributions[unit_id] = contributions.get(unit_id, 0) + weight / (RRF_K + rank)
            detail = {"rank": rank}
            raw_score = channel_scores.get(channel, {}).get(unit_id)
            if channel == "temporal":
                detail["mode"] = temporal_intent["mode"]
                detail["date"] = str(result_by_id[unit_id].get("date") or "")
            else:
                detail["raw_score"] = round(float(raw_score or 0), 6)
            if channel == "graph":
                detail["via"] = str(result_by_id[unit_id].get("related_via") or "")
                detail["seed"] = str(
                    result_by_id[unit_id].get("related_seed") or ""
                )
                confidence = result_by_id[unit_id].get("related_confidence")
                if confidence is not None:
                    detail["confidence"] = round(float(confidence), 6)
                path = result_by_id[unit_id].get("related_path")
                if path:
                    detail["path"] = path
            if channel == "experience":
                detail["via"] = str(
                    result_by_id[unit_id].get("related_experience") or ""
                )
            evidence.setdefault(unit_id, {})[channel] = detail

    results = []
    result_scores = {}
    for unit_id, result in result_by_id.items():
        unit_evidence = evidence.get(unit_id, {})
        if not unit_evidence:
            continue
        item = dict(result)
        item["retrieval_channels"] = [
            channel for channel in RETRIEVAL_CHANNELS if channel in unit_evidence
        ]
        item["retrieval_evidence"] = unit_evidence
        fusion_score = contributions.get(unit_id, 0) * RRF_SCORE_SCALE
        lexical_quality = min(
            float(channel_scores.get("lexical", {}).get(unit_id, 0)),
            100,
        )
        structured_quality = min(
            float(channel_scores.get("structured", {}).get(unit_id, 0)),
            100,
        )
        graph_quality = min(
            float(channel_scores.get("graph", {}).get(unit_id, 0)),
            100,
        )
        anchor_quality = lexical_quality or structured_quality or graph_quality or 1
        item["fusion_score"] = round(fusion_score, 6)
        item["score"] = round(anchor_quality * (1 + fusion_score / 20), 6)
        direct_channels = {"lexical", "structured", "type", "temporal"}
        if direct_channels & set(item["retrieval_channels"]):
            item["match_kind"] = "direct"
        elif "experience" in item["retrieval_channels"]:
            item["match_kind"] = "experience"
        else:
            item["match_kind"] = "graph"
        results.append(item)
        result_scores[unit_id] = item["score"]

    for item in results:
        if not item.get("related_path"):
            continue
        seed_score = float(result_scores.get(item.get("related_seed"), 0) or 0)
        if not seed_score:
            continue
        confidence = float(item.get("related_confidence") or 0)
        hop_decay = 0.85 ** max(0, len(item["related_path"]) - 1)
        calibrated_score = seed_score * confidence * hop_decay
        if calibrated_score > item["score"]:
            item["score"] = round(calibrated_score, 6)
    return results


def score_unit(unit, query_text, query_terms, *, term_weights=None):
    query_terms = expand_compound_terms(query_terms)
    unit_terms = expand_compound_terms(unit.get("terms") or [])
    text = normalize(" ".join([unit.get("title", ""), unit.get("summary", "")]))
    overlap = query_terms & unit_terms
    if term_weights is None:
        score = len(overlap) * 5
    else:
        score = sum(float(term_weights.get(term, 0)) for term in overlap) * 5

    if query_text and query_text in text:
        score += 8
    for token in query_terms:
        if token and token in text:
            score += 2
    for token in unit_terms:
        token = normalize(token)
        if len(token) >= 2 and token in query_text:
            score += 2

    if score <= 0:
        return 0

    score += {
        "decision": 4,
        "error": 3,
        "preference": 3,
        "project_rule": 3,
        "environment": 3,
        "skill": 3,
        "workflow": 3,
        "insight": 3,
    }.get(unit.get("type"), 0)
    return score


def query_term_weights(query_terms, units):
    """Weight query terms by inverse frequency among eligible formal memory."""
    expanded_query = expand_compound_terms(query_terms)
    if not expanded_query or not units:
        return {}
    document_terms = [
        expand_compound_terms(unit.get("terms") or [])
        for unit in units
    ]
    document_count = len(document_terms)
    weights = {}
    for term in expanded_query:
        frequency = sum(term in terms for terms in document_terms)
        weights[term] = math.log1p(
            (document_count - frequency + 0.5) / (frequency + 0.5)
        )
    return weights


def expand_compound_terms(terms):
    expanded = {str(term) for term in terms if str(term)}
    for term in tuple(expanded):
        if not re.fullmatch(r"[a-z0-9_-]+", term, re.IGNORECASE):
            continue
        expanded.update(
            part.casefold()
            for part in re.split(r"[_-]+", term)
            if len(part) >= 3
        )
    return expanded


def is_runtime_unit(unit):
    if not is_valid_runtime_record(unit):
        return False
    return bool(runtime_source_path(unit))


def expand_graph_results(index, direct_results, project="", *, allowed_projects=None):
    """Add units only through revision-safe, explicitly declared relations."""
    graph = index.get("_graph") or {}
    edges = graph.get("edges") or []
    if not direct_results or not edges:
        return direct_results

    units = {
        unit.get("id"): unit
        for unit in index.get("units", [])
        if unit.get("id") and is_runtime_unit(unit)
    }

    by_id = {item.get("id"): item for item in direct_results}

    direct_scores = {
        item.get("id"): float(item.get("score") or 0)
        for item in direct_results
        if item.get("id")
    }
    allowed_graph_ids = {
        unit_id
        for unit_id, unit in units.items()
        if _unit_allowed(unit, project, allowed_projects)
    }
    semantic_paths = semantic_memory_paths(
        graph,
        [item.get("id") for item in direct_results],
        units.values(),
        max_hops=2,
        validated=bool(index.get("_graph_validated")),
        allowed_node_ids=allowed_graph_ids,
        seed_scores=direct_scores,
    )
    for unit_id, match in sorted(semantic_paths.items()):
        unit = units.get(unit_id)
        if (
            not unit
            or not _unit_allowed(unit, project, allowed_projects)
        ):
            continue
        confidence = float(match.get("confidence") or 0)
        hop_decay = 0.85 ** max(0, len(match["path"]) - 1)
        graph_score = (
            direct_scores.get(match.get("seed"), 0)
            * confidence
            * hop_decay
        )
        existing = by_id.get(unit_id)
        if existing and float(existing.get("score") or 0) >= graph_score:
            continue
        result = dict(existing or unit)
        result["score"] = max(float(result.get("score") or 0), graph_score)
        result["graph_score"] = graph_score
        result["match_kind"] = (
            result.get("match_kind")
            if existing
            else "graph"
        )
        result["related_path"] = list(match["path"])
        result["related_seed"] = match["seed"]
        result["related_confidence"] = confidence
        result["related_via"] = " -> ".join(
            step["relation"] for step in match["path"]
        )
        by_id[unit_id] = result

    return list(by_id.values())


def validate_recall_index(index):
    if not isinstance(index, dict):
        raise ValueError("recall index must be a JSON object")
    if index.get("schema_version") != RUNTIME_SCHEMA_VERSION:
        raise ValueError(
            f"recall index schema must be {RUNTIME_SCHEMA_VERSION}"
        )
    if not isinstance(index.get("units"), list):
        raise ValueError("recall index units must be a list")
    seen_ids = set()
    for unit in index["units"]:
        unit_id = str(unit.get("id") or "") if isinstance(unit, dict) else ""
        if unit_id and unit_id in seen_ids:
            raise ValueError(f"duplicate recall unit ID: {unit_id}")
        if unit_id:
            seen_ids.add(unit_id)
    if "experience_bundles" in index and not isinstance(
        index.get("experience_bundles"), list
    ):
        raise ValueError("recall index experience_bundles must be a list")
    validate_experience_bundles(index.get("experience_bundles"), index.get("units"))
    if "conversation_summaries" not in index:
        if "conversation_summary_count" in index:
            raise ValueError(
                "recall index conversation_summary_count requires "
                "conversation_summaries"
            )
        return
    summaries = index.get("conversation_summaries")
    if not isinstance(summaries, list):
        raise ValueError("recall index conversation_summaries must be a list")
    count = index.get("conversation_summary_count")
    if (
        isinstance(count, bool)
        or not isinstance(count, int)
        or count != len(summaries)
    ):
        raise ValueError("recall index conversation summary count is invalid")
    seen_summary_ids = set()
    seen_session_ids = set()
    for record in summaries:
        if not _valid_indexed_conversation_summary(record):
            raise ValueError("recall index conversation summary is invalid")
        if record["id"] in seen_ids:
            raise ValueError(
                "conversation summary ID collision with formal recall unit"
            )
        if record["id"] in seen_summary_ids:
            raise ValueError("duplicate conversation summary ID")
        if record["session_id"] in seen_session_ids:
            raise ValueError("duplicate conversation summary session ID")
        seen_summary_ids.add(record["id"])
        seen_session_ids.add(record["session_id"])


def _valid_indexed_conversation_summary(record):
    return validate_conversation_summary_record(record)


def _canonical_projects(projects):
    if projects is None:
        return None
    normalized = set()
    for value in projects:
        raw = str(value or "").strip()
        project = canonical_project(raw)
        if raw and project:
            normalized.add(project)
    return frozenset(normalized)


def _unit_allowed(unit, project, allowed_projects):
    if project:
        if allowed_projects is not None and project not in allowed_projects:
            return False
        return unit.get("project") == project
    if allowed_projects is None:
        return True
    return unit.get("scope") == "global" or unit.get("project") in allowed_projects


def dedupe_results(results):
    seen = set()
    unique = []
    for item in results:
        key = (
            item.get("type", ""),
            normalize(item.get("title", "")),
            normalize(item.get("summary", "")),
            item.get("project", ""),
        )
        if key in seen:
            continue
        seen.add(key)
        unique.append(item)
    return unique


def bounded_result_selection(results, limit, *, reserved_ids=None):
    """Reserve bounded explicit companions without dropping every anchor."""
    limit = max(0, int(limit or 0))
    if not limit:
        return []
    reserved_ids = set(reserved_ids or [])
    if not reserved_ids or limit < 2:
        return list(results[:limit])
    companions = [item for item in results if item.get("id") in reserved_ids]
    reserve = min(2, len(companions), limit - 1)
    required = companions[:reserve]
    required_ids = {item.get("id") for item in required}
    direct = [item for item in results if item.get("id") not in required_ids]
    return [*direct[: limit - reserve], *required]


def recall_source_rank(item):
    source = " ".join(
        [
            str(item.get("path") or ""),
            str(item.get("source_note") or ""),
        ]
    ).replace("\\", "/")
    if "/Memory/decisions" in source or "/Memory/pitfalls" in source:
        return 3
    if "05-Agent-Memory/" in source:
        return 2
    return 1


def insight_maturity_rank(item):
    if item.get("type") != "insight":
        return 0
    return 1 if item.get("maturity") == "reinforced" else 0


def explain_retrieval(item, query_terms):
    """Render deterministic, user-readable evidence for one recall result."""
    channels = item.get("retrieval_channels") or []
    reasons = []
    if "lexical" in channels:
        matched = sorted(
            expand_compound_terms(query_terms)
            & expand_compound_terms(item.get("terms") or [])
        )[:4]
        detail = f"（{'、'.join(matched)}）" if matched else ""
        reasons.append(f"内容关键词匹配{detail}")
    if "structured" in channels:
        reasons.append("名称或结构字段匹配")
    if "type" in channels:
        reasons.append("记忆类型符合请求")
    if "temporal" in channels:
        mode = (
            (item.get("retrieval_evidence") or {})
            .get("temporal", {})
            .get("mode", "")
        )
        temporal_reason = {
            "latest": "时间条件匹配最近记录",
            "earliest": "时间条件匹配最早记录",
            "date": "日期条件匹配",
        }.get(mode, "时间条件匹配")
        reasons.append(temporal_reason)
    if "graph" in channels:
        path = item.get("related_path") or []
        if path:
            relations = " → ".join(step.get("relation", "") for step in path)
            reasons.append(f"关系路径（{relations}）")
        else:
            reasons.append("知识图谱关联")
    if "experience" in channels:
        reasons.append("同一任务经验链")
    return "；".join(reasons) or "正式记忆直接匹配"


def explain_authority(item):
    """Expose normalized ownership without changing the memory contract."""
    try:
        authority = normalize_authority_metadata(item)
    except ValueError:
        authority = {}
    if not authority:
        return {"role": "unspecified", "owner": "", "route": ""}
    return {
        "role": authority["authority_role"],
        "owner": authority["authority_owner"],
        "route": authority_route(item),
    }


def format_authority(authority):
    if not isinstance(authority, dict):
        return "unspecified"
    role = str(authority.get("role") or "unspecified")
    route = str(authority.get("route") or "")
    owner = str(authority.get("owner") or "")
    if route:
        return f"{role} via {route}"
    if owner:
        return f"{role} by {owner}"
    return role


def format_results(results):
    if not results:
        return "No related memory found.\n"
    lines = []
    for item in results:
        lines.extend(
            [
                f"[{item['score']}] {item.get('type', '')}: {item.get('title', '')}",
                f"  project: {item.get('project', '') or '-'}",
                f"  source: {item.get('path', '')}",
                f"  channels: {', '.join(item.get('retrieval_channels') or []) or '-'}",
                f"  why_recalled: {item.get('why_recalled', '-')}",
                f"  authority: {format_authority(item.get('authority'))}",
                f"  summary: {item.get('recall_summary', item.get('summary', ''))}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def normalize(text):
    text = str(text or "").lower()
    text = re.sub(r"\s+", " ", text).strip()
    return text


def vault_from_config():
    try:
        from config import load_config

        return load_config().get("vault_path")
    except Exception:
        return ""


def main():
    parser = argparse.ArgumentParser(description="Recall relevant Obsidian memory.")
    parser.add_argument("query", help="query text")
    parser.add_argument("--project", default="", help="optional project slug filter")
    parser.add_argument("--limit", type=int, default=8, help="maximum results")
    parser.add_argument(
        "--vault",
        default="",
        help="vault path; defaults to scripts/config.yaml vault_path",
    )
    parser.add_argument(
        "--index",
        default="",
        help="direct recall-index.json path; overrides --vault",
    )
    parser.add_argument("--json", action="store_true", help="print JSON results")
    args = parser.parse_args()

    index_source = args.index or args.vault or vault_from_config()
    if not index_source:
        print("ERROR: no vault path configured", file=sys.stderr)
        return 2
    index = load_recall_index(index_source)
    results = recall(args.query, index, project=args.project, limit=args.limit)
    if args.json:
        print(json.dumps(results, ensure_ascii=False, indent=2))
    else:
        print(format_results(results), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
