#!/usr/bin/env python3
"""Query the lightweight Obsidian recall index.

This is a small Cognee-inspired retrieval layer: it does not require a vector
database, graph database, Docker, or an LLM. It ranks structured memory units
generated by knowledge_index.py.
"""
import argparse
import json
import os
import re
import sys

from knowledge_index import extract_terms, type_rank


DEFAULT_INDEX = os.path.join("05-Agent-Memory", "recall-index.json")


def load_recall_index(vault_or_index_path):
    """Load recall-index.json from a vault path or direct file path."""
    path = os.path.expanduser(os.path.expandvars(str(vault_or_index_path or "")))
    if os.path.isdir(path):
        path = os.path.join(path, DEFAULT_INDEX)
    if not os.path.exists(path):
        raise FileNotFoundError(f"recall index not found: {path}")
    with open(path, "r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"recall index is not a JSON object: {path}")
    data["_path"] = path
    return data


def recall(query, index, project="", limit=8):
    """Return ranked recall units for a query."""
    query = str(query or "").strip()
    if not query:
        return []
    query_terms = set(extract_terms(query, limit=40))
    query_text = normalize(query)
    results = []

    for unit in index.get("units", []):
        if project and unit.get("project") != project:
            continue
        score = score_unit(unit, query_text, query_terms)
        if score <= 0:
            continue
        result = dict(unit)
        result["score"] = score
        results.append(result)

    results.sort(
        key=lambda item: (
            item["score"],
            type_rank(item.get("type", "")),
            str(item.get("date", "")),
            str(item.get("title", "")),
        ),
        reverse=True,
    )
    return dedupe_results(results)[: int(limit or 8)]


def score_unit(unit, query_text, query_terms):
    unit_terms = set(unit.get("terms") or [])
    text = normalize(" ".join([unit.get("title", ""), unit.get("summary", "")]))
    overlap = query_terms & unit_terms
    score = len(overlap) * 5

    if query_text and query_text in text:
        score += 8
    for token in query_terms:
        if token and token in text:
            score += 2

    score += {
        "decision": 4,
        "error": 3,
        "personal-memory": 3,
        "memory-candidate": 1,
    }.get(unit.get("type"), 0)
    return score


def dedupe_results(results):
    seen = set()
    unique = []
    for item in results:
        key = (
            item.get("type", ""),
            normalize(item.get("title", "")),
            normalize(item.get("summary", "")),
            item.get("project", ""),
        )
        if key in seen:
            continue
        seen.add(key)
        unique.append(item)
    return unique


def format_results(results):
    if not results:
        return "No related memory found.\n"
    lines = []
    for item in results:
        lines.extend(
            [
                f"[{item['score']}] {item.get('type', '')}: {item.get('title', '')}",
                f"  project: {item.get('project', '') or '-'}",
                f"  source: {item.get('path', '')}",
                f"  summary: {item.get('summary', '')}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def normalize(text):
    text = str(text or "").lower()
    text = re.sub(r"\s+", " ", text).strip()
    return text


def vault_from_config():
    try:
        from config import load_config

        return load_config().get("vault_path")
    except Exception:
        return ""


def main():
    parser = argparse.ArgumentParser(description="Recall relevant Obsidian memory.")
    parser.add_argument("query", help="query text")
    parser.add_argument("--project", default="", help="optional project slug filter")
    parser.add_argument("--limit", type=int, default=8, help="maximum results")
    parser.add_argument(
        "--vault",
        default="",
        help="vault path; defaults to scripts/config.yaml vault_path",
    )
    parser.add_argument(
        "--index",
        default="",
        help="direct recall-index.json path; overrides --vault",
    )
    parser.add_argument("--json", action="store_true", help="print JSON results")
    args = parser.parse_args()

    index_source = args.index or args.vault or vault_from_config()
    if not index_source:
        print("ERROR: no vault path configured", file=sys.stderr)
        return 2
    index = load_recall_index(index_source)
    results = recall(args.query, index, project=args.project, limit=args.limit)
    if args.json:
        print(json.dumps(results, ensure_ascii=False, indent=2))
    else:
        print(format_results(results), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
